- name: update system
  sudo: yes
  yum: name=* state=latest

- name: install development tools
  sudo: yes
  yum: name="@Development tools" state=present

- name: install other dev tools
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
    - mercurial
    - screen
    - autoconf
    - kernel-devel
    - automake
    - libtool
    - make
    - gcc
    - vim
    - golang
    - cmockery2
    - cmockery2-devel
    - boost-devel
    - glib2-devel
    - zeromq3-devel
    - libevent-devel
    - gcc-c++
    - nodejs
    - npm
    - indent
    - ruby
    - cscope

- name: copy screenrc
  copy: src=screenrc dest=/home/vagrant/.screenrc force=no

- name: copy .bashrc
  copy: src=bashrc dest=/home/vagrant/.bashrc force=yes

- name: copy vimrc
  copy: src=vimrc dest=/home/vagrant/.vimrc force=no

- name: setup vim
  unarchive: src=vim.tar.gz dest=/home/vagrant creates=/home/vagrant/.vim/doc/bufexplorer.txt

- name: copy gitconfig
  copy: src={{ lookup('env','HOME') }}/.gitconfig dest=/home/vagrant/.gitconfig owner=vagrant group=vagrant mode=0600 force=no

- name: copy ssh
  copy: src={{ lookup('env','HOME') }}/.ssh/id_rsa dest=/home/vagrant/.ssh/id_rsa owner=vagrant group=vagrant mode=0600 force=no
